import { Command } from 'commander';
import fs from 'node:fs';
import path from 'node:path';
import { prompt } from '../lib/prompt.js';
import { fail, info, ok, section } from '../lib/theme.js';

interface AgentManifest {
  name: string;
  description: string;
  tags?: string;
  category?: string;
  language?: string;
  agent?: string;
  is_free?: boolean;
  price_usd?: number;
  requirements?: string[];
  useCases?: Array<{ title: string; description: string }>;
  links?: {
    github?: string;
    docs?: string;
    website?: string;
  };
}

interface PromptManifest {
  name: string;
  description: string;
  prompt?: string;
  tags?: string;
  category?: string;
  is_free?: boolean;
  price_usd?: number;
  useCases?: Array<{ title: string; description: string }>;
  links?: {
    github?: string;
    docs?: string;
    website?: string;
  };
}

interface TokenManifest {
  name: string;
  description: string;
  ticker: string;
  quote_mint?: string;
  fee_selection?: string;
  image?: string;
}

function generateAgentManifest(
  name: string,
  description: string,
  tags?: string,
): AgentManifest {
  const manifest: AgentManifest = {
    name,
    description,
    tags: tags || 'automation,ai',
    category: 'General',
    language: 'Python',
    agent: '# Your agent code here\n# Example:\n# from swarms import Agent\n# agent = Agent(...)',
    is_free: true,
    useCases: [
      {
        title: 'Example Use Case',
        description: 'Describe how this agent can be used',
      },
    ],
    links: {
      github: 'https://github.com/yourusername/your-agent',
      docs: 'https://docs.example.com',
    },
  };
  return manifest;
}

function generatePromptManifest(
  name: string,
  description: string,
  tags?: string,
): PromptManifest {
  const manifest: PromptManifest = {
    name,
    description,
    prompt: 'Your prompt template here...',
    tags: tags || 'productivity,writing',
    category: 'General',
    is_free: true,
    useCases: [
      {
        title: 'Example Use Case',
        description: 'Describe how this prompt can be used',
      },
    ],
    links: {
      github: 'https://github.com/yourusername/your-prompt',
    },
  };
  return manifest;
}

function generateTokenManifest(
  name: string,
  description: string,
  ticker: string,
): TokenManifest {
  const manifest: TokenManifest = {
    name,
    description,
    ticker: ticker.toUpperCase(),
    quote_mint: 'SOL',
    fee_selection: 'market',
  };
  return manifest;
}

function generateReadme(type: 'agent' | 'prompt' | 'token'): string {
  let content = `# Swarms Marketplace ${type.charAt(0).toUpperCase() + type.slice(1)} Manifest\n\n`;
  content += `This manifest was generated by \`swarms init ${type}\`.\n\n`;
  content += '## Required Fields\n\n';
  
  if (type === 'agent') {
    content += '- **name**: Agent name (≥2 chars)\n';
    content += '- **description**: What your agent does\n';
    content += '- **agent**: Your agent code (Python recommended)\n';
    content += '\n## Optional Fields\n\n';
    content += '- **tags**: Comma-separated tags for discovery\n';
    content += '- **category**: Agent category (e.g., "Automation", "Data Analysis")\n';
    content += '- **language**: Programming language (default: "Python")\n';
    content += '- **is_free**: Set to true for free agents (default: true)\n';
    content += '- **price_usd**: Price in USD (requires is_free: false)\n';
    content += '- **requirements**: Array of package dependencies\n';
    content += '- **useCases**: Array of {title, description} objects\n';
    content += '- **links**: {github, docs, website}\n';
  } else if (type === 'prompt') {
    content += '- **name**: Prompt name (≥2 chars)\n';
    content += '- **description**: What your prompt does\n';
    content += '- **prompt**: Your prompt template\n';
    content += '\n## Optional Fields\n\n';
    content += '- **tags**: Comma-separated tags for discovery\n';
    content += '- **category**: Prompt category (e.g., "Writing", "Coding")\n';
    content += '- **is_free**: Set to true for free prompts (default: true)\n';
    content += '- **price_usd**: Price in USD (requires is_free: false)\n';
    content += '- **useCases**: Array of {title, description} objects\n';
    content += '- **links**: {github, docs, website}\n';
  } else {
    content += '- **name**: Token/Agent name\n';
    content += '- **description**: What your tokenized agent does\n';
    content += '- **ticker**: Token symbol (1-10 uppercase chars)\n';
    content += '\n## Optional Fields\n\n';
    content += '- **quote_mint**: "SOL" or "USDC" (default: "SOL")\n';
    content += '- **fee_selection**: "market" or "frenzy" (default: "market")\n';
    content += '- **image**: Image URL or base64 data URL\n';
  }
  
  content += '\n## Next Steps\n\n';
  content += `1. Edit \`${type}.json\` to customize your ${type}\n`;
  content += `2. Run \`swarms launch ${type} --manifest ${type}.json\`\n`;
  content += '\n## Documentation\n\n';
  content += 'For more information, visit: https://docs.swarms.ai/docs/marketplace\n';
  
  return content;
}

function writeManifest(
  filePath: string,
  manifest: AgentManifest | PromptManifest | TokenManifest,
  type: 'agent' | 'prompt' | 'token',
): void {
  const json = JSON.stringify(manifest, null, 2);
  fs.writeFileSync(filePath, json + '\n', 'utf8');
  
  const readmePath = path.join(path.dirname(filePath), `${type.toUpperCase()}_MANIFEST.md`);
  const readme = generateReadme(type);
  fs.writeFileSync(readmePath, readme, 'utf8');
}

export function registerInit(program: Command): void {
  program
    .command('init')
    .description('Bootstrap a marketplace manifest in the current directory.')
    .argument('[type]', 'Manifest type: agent, prompt, or token')
    .option('--name <name>', 'Product name')
    .option('--description <text>', 'Product description')
    .option('--ticker <TICKER>', 'Token symbol (for token type only)')
    .option('--tags <csv>', 'Comma-separated tags')
    .option('-f, --force', 'Overwrite existing manifest file')
    .action(
      async (
        type?: string,
        opts?: {
          name?: string;
          description?: string;
          ticker?: string;
          tags?: string;
          force?: boolean;
        },
      ) => {
        try {
          const options = opts || {};
          let manifestType = type;

          if (!manifestType) {
            console.log('');
            console.log(section('Initialize Swarms Manifest'));
            console.log('');
            manifestType = await prompt(
              'What type of manifest? (agent/prompt/token):',
            );
          }

          manifestType = manifestType.toLowerCase().trim();

          if (!['agent', 'prompt', 'token'].includes(manifestType)) {
            throw new Error(
              'Invalid type. Must be one of: agent, prompt, token',
            );
          }

          const fileName =
            manifestType === 'agent'
              ? 'agent.json'
              : manifestType === 'prompt'
                ? 'prompt.json'
                : 'token.json';
          const filePath = path.join(process.cwd(), fileName);

          if (fs.existsSync(filePath) && !options.force) {
            throw new Error(
              `${fileName} already exists. Use --force to overwrite.`,
            );
          }

          let name = options.name;
          let description = options.description;
          let ticker = options.ticker;
          const tags = options.tags;

          if (!name) {
            name = await prompt('Name:');
          }
          if (!name || name.trim().length < 2) {
            throw new Error('Name must be at least 2 characters.');
          }

          if (!description) {
            description = await prompt('Description:');
          }
          if (!description || !description.trim()) {
            throw new Error('Description is required.');
          }

          if (manifestType === 'token') {
            if (!ticker) {
              ticker = await prompt('Ticker symbol (1-10 chars):');
            }
            if (!ticker || !/^[A-Za-z0-9]{1,10}$/.test(ticker)) {
              throw new Error(
                'Ticker must be 1-10 alphanumeric characters.',
              );
            }
          }

          let manifest:
            | AgentManifest
            | PromptManifest
            | TokenManifest;

          if (manifestType === 'agent') {
            manifest = generateAgentManifest(name, description, tags);
          } else if (manifestType === 'prompt') {
            manifest = generatePromptManifest(name, description, tags);
          } else {
            manifest = generateTokenManifest(name, description, ticker!);
          }

          writeManifest(
            filePath,
            manifest,
            manifestType as 'agent' | 'prompt' | 'token',
          );

          console.log('');
          console.log(ok(`Created ${fileName}`));
          console.log(ok(`Created ${manifestType.toUpperCase()}_MANIFEST.md`));
          console.log('');
          console.log(
            info(
              'Edit the manifest and see the README for field documentation.',
            ),
          );
          console.log('');
          console.log(
            info(
              `Next step: swarms launch ${manifestType} --manifest ${fileName}`,
            ),
          );
          console.log('');
        } catch (err) {
          console.log('');
          console.log(fail(err instanceof Error ? err.message : String(err)));
          process.exitCode = 1;
        }
      },
    );
}
